--- 
:backgroundrb: 
  :ip: 0.0.0.0
  :port: 11006
:schedules:
  :mailman_worker:
    :check_queue:
      :trigger_args:
        :start: <%= Time.now + 1.minute %>
        :end: <%= Time.now + 1.year %>
        :repeat_interval: <%= 1.minute %>
