# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "events", :force => true do |t|
    t.column "name",       :string,   :limit => 200
    t.column "slug",       :string,   :limit => 16
    t.column "starts_on",  :date
    t.column "location",   :string,   :limit => 200
    t.column "contact",    :string,   :limit => 200
    t.column "email",      :string,   :limit => 200
    t.column "created_at", :datetime
  end

  add_index "events", ["slug"], :name => "index_events_on_slug"

  create_table "requests", :force => true do |t|
    t.column "ride_id", :integer
    t.column "name",    :string,  :limit => 200
    t.column "email",   :string,  :limit => 200
    t.column "phone",   :string,  :limit => 36
    t.column "seats",   :integer, :limit => 1
    t.column "comment", :text
  end

  create_table "rides", :force => true do |t|
    t.column "event_id",    :integer
    t.column "driver",      :string,   :limit => 200
    t.column "email",       :string,   :limit => 200
    t.column "phone",       :string,   :limit => 36
    t.column "location",    :string
    t.column "seats",       :integer,  :limit => 1
    t.column "comment",     :text
    t.column "created_at",  :datetime
    t.column "modified_at", :datetime
    t.column "auth",        :string,   :limit => 36
  end

  add_index "rides", ["auth"], :name => "index_rides_on_auth"
  add_index "rides", ["event_id"], :name => "index_rides_on_event_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"
  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

end
