# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 0) do

  create_table "drivers", :force => true do |t|
    t.column "person_id", :integer
    t.column "ride_id",   :integer
  end

end
